### PR TITLE
BatoTo

### PR DESCRIPTION
**Pull request by niclimcy**
Fully working now, no more email spam bye

### CODE REVIEW

**Comment by TheNetsky** [comment]
- You've modified the cheerio package, this will likely affect all the other sources.
- Also please use language flags instead of languages strings
- Since you're working with a multi lang source, having the language flag or anything similar on the manga subtitles on HomeScreen, ViewMore and Search is a very nice thing to have. Now user have to open each manga to see the language it's in.

**Comment by niclimcy** [comment]
> * You've modified the cheerio package, this will likely affect all the other sources.
> * Also please use language flags instead of languages strings
> * Since you're working with a multi lang source, having the language flag or anything similar on the manga subtitles on HomeScreen, ViewMore and Search is a very nice thing to have. Now user have to open each manga to see the language it's in.

but originally package-lock had 0.2.31 but package.json had 0.2.21 of cheerio types defined, so which version should I use?

**Comment by TheNetsky** [comment]
Always package.json. I'll remove the package-lock next time.

**Comment by niclimcy** [comment]
I have no idea why the selectors are setting the wrong flags hm (for homepage only)

**Pull request closed without merging**
