### PR TITLE
extra features

### PR DESCRIPTION
**Pull request by hammyo-o**
added skip read manga toggle (reset to default does not reset read manga)
added sort by month
added page numbers below manga
added amount of favorites to description of each manga
added popular monthly and popular all-time to homepage

issues: persistent "JSManagedValue was released" when interacting with reset to default and content settings. occasional crashing/freezing when editing additional arguments. restart fixes.

### CODE REVIEW

**Comment by TheNetsky** [comment]
Don't PR into the gh-pages branch, you PR into the correct version of a branch.

**Comment by celarye** [comment]
Squashing those commits couldn't hurt either...

**Comment by TheNetsky** [comment]
> Squashing those commits couldn't hurt either...

I can do that on merge too

**Comment by celarye** [comment]
I personally think that de developer should do that locally and that the maintainer then just either merges or rebases the PR.

**Pull request closed without merging**
